### ISSUE TITLE
WoRMS did not merge on the XCOL-2023-11-29 extended release

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/xcol#105]
Since last week [WoRMS](https://www.gbif.org/dataset/2d59e5db-57ad-41ff-97d6-11f5fb264527) license has change to cc by so now it should be possible to use it as a xcol source.

At first glance the sector [synced properly](https://www.dev.checklistbank.org/catalogue/3/sector/sync?sectorKey=1998):

<img width="800" alt="Captura de pantalla 2023-11-30 a la(s) 10 49 51 a m" src="https://github.com/CatalogueOfLife/xcol/assets/5700527/281bdc27-5e32-4e20-b976-7c9ae846db26">

Nevertheless the final assembly does show any taxa from this source:

I check this directly on the [source search](https://www.dev.checklistbank.org/dataset/274825/names?SECTOR_DATASET_KEY=2011&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&sortBy=taxonomic) an on the assembly looking

<img width="800" alt="Captura de pantalla 2023-11-30 a la(s) 10 51 04 a m" src="https://github.com/CatalogueOfLife/xcol/assets/5700527/8f9e673c-4d37-480d-b6e4-dbbeddb4da64">

**Comment by mdoering** [comment]
It did merge like the sync metrics suggeste. But for some reason it is listed under the wrong source.
The species _Cardioecia watersi_ for example is declared as coming from ITIS: https://www.dev.checklistbank.org/dataset/274825/taxon/~W_Y

**Comment by mdoering** [comment]
Hm, the sector ids have apparently changed. The sector 1998 in the release is entirely different from the one in the project:

https://api.dev.checklistbank.org/dataset/274825/sector/1998
https://api.dev.checklistbank.org/dataset/3/sector/1998

**Comment by mdoering** [comment]
Ah, it is also like that in the October base release:
https://api.dev.checklistbank.org/dataset/272972/sector/1998

The problem is that we have copied the October release from PROD, but did not copy the latest project changes (which we can't). So we have used the same sector id for a merge sector on DEV and for some ITIS sector on PROD. If we had just run this on PROD it would have been fine. Difficult to fix on dev to be honest. Maybe the best would is to do a new regular release as the new base from the project. It will have old data from August only, but I suppose that's not a big problem. To have a proper xcol we need to switch to use prod, but I would like to make sure we don't mess up Yuris work by doing so. Primarily I am concerned about impacts on the UI for thousands of new sectors. @thomasstjerne We might need to change sth there to filter out the merge ones?

**Comment by mdoering** [comment]
92,607 names from WoRMS in the release from 4th December: https://www.dev.checklistbank.org/dataset/275521/names?SECTOR_DATASET_KEY=2011&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&sortBy=taxonomic

**Comment by camiplata** [comment]
awesome, thanks
