### ISSUE TITLE
misspelled family Protoperidinaceae

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/xcol#114]
The XCOL contains the family `Protoperidiniaceae J.P.Bujak & E.H.Davies` additionally as
`Protoperidinaceae Taylor, 1987` which is a misspelling.

Create a decision to update the misspelled name

**Comment by DianRHR** [comment]
The family Protoperidiniaceae J.P. Bujak & E.H. Davies comes from the base [COL ](https://www.checklistbank.org/dataset/296511/taxon/CBVCD) and the correct name is the one merged from [WoRMS](https://www.checklistbank.org/dataset/298210/taxon/CQYHB). 
The correction must be made in ITIS.  @DaveNicolson can you check this one please?

**Comment by DaveNicolson** [comment]
The ITIS name was misspelled and had incorrect authorship. It's being addressed in the load we're about to start, expect it to be fixed online by the end of the month.

**Comment by DianRHR** [comment]
I created a decision on the project to "block" that name to be merged in the xrelease.

**Comment by DaveNicolson** [comment]
It is corrected in the version of ITIS that Geoff is now (or will soon) process for use in the next version of COL.

**Comment by DaveNicolson** [comment]
This issue was resolved in ITIS: https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=1229981#null

The error is now in synonymy under the name w/correct spelling & authorship (Geoff got the data already, not sure where it is in processing). Will you still need to manually block/manipulate around it?
