### ISSUE TITLE
Dynamically exclude Plazi sectors

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/xcol#139]
Add project setting to activate a publisher sector filter based on issues & metrics.
@camiplata can you describe how the exact filtering works currently?

**Comment by camiplata** [comment]
For every plazi and bdj dataset the error and warning issues related to name and name usage are use to evaluate is the dataset can be use or not for the xrelease

[name_issues_warning.csv](https://github.com/user-attachments/files/16147206/name_issues_warning.csv)
[name_issues_error.csv](https://github.com/user-attachments/files/16147207/name_issues_error.csv)

- A list of all Plazi datasets is retrieved via the API.
- All the issues count for each Plazi dataset within the above categories (error and warning) are retreived via the API.
-  All the issues count within each given category are evaluated as a proportion of the nameCount of the dataset, issue count / name Count. Then all the proportion of each issue category (error warning) are summed.
-  If the summ of error issues is more than 0,4 the dataset is excluded
-  If the sum of error issues is lower than than 0,4  but the sum of both error and warning issues is more than than 0,4 the dataset is excluded

#What can be improved

- Use only error issues for evaluating the datasets, using warning issues takes away some useful datasets
- Evaluate the issues as a proportion of speciesCount instead of nameCount, most of the issues and relevant information is at the species level, so this can give a closer aproximation to the dataset quality.

**Comment by camiplata** [comment]
I have done a detailed review of several Plazi datasets that have low quality (high number of error and warning issues) and I found that it is not necessary to exclude specific datasets, all the unwanted names have been already filter out by the error issue exclusion set at the config file.

I think the Dynamically exclude Plazi sectors or a manual one is not needed. 
But assessing Plazi datasets once in a while to report back to Plazi is desirable
