### ISSUE TITLE
Authorship year typo creates new species

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/xcol#142]
When the authorships year differs considerably, but is just 2 flipped numbers, e.g- 89 vs 98, we end up with 2 distinct species:

![Image](https://github.com/CatalogueOfLife/xcol/assets/327505/7a4e22bb-aa5b-48db-b1bc-0e0a824c6747)

**Comment by camiplata** [comment]
A duplicate is created due to a 2 year difference.
In this case is the name,  and authorship except for the year are the same, I'll suggest to merge the information or keep only the name from the source with higher priority, specially is is an **attach** kind of sector

![Captura de pantalla 2024-07-10 a la(s) 4 07 49 p m](https://github.com/CatalogueOfLife/xcol/assets/5700527/c09b5500-d436-42d3-baa9-355e1aa59bc1)

**Comment by mdoering** [comment]
I have modified the merge to ignore any subsequent, accepted (infra)species with the same name, but different authorship - if they are in the same family subtree. We might even want to broaden the scope, but so far most duplicates live even in the same genus.

**Comment by mdoering** [comment]
https://github.com/CatalogueOfLife/backend/commit/4fa03e2565bdbbc3c24a98e5fb7a6ab908da9091
